package me.giraffetree.java.jnaplus.complex;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.IntByReference;
/**
 * JNA Wrapper for library <b>Complex</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ComplexLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "libComplex";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ComplexLibrary.JNA_LIBRARY_NAME);
	public static final ComplexLibrary INSTANCE = (ComplexLibrary)Native.loadLibrary(ComplexLibrary.JNA_LIBRARY_NAME, ComplexLibrary.class);
	IntByReference getArray(int len);
}
