package me.giraffetree.java.jnaplus.basic;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class User extends Structure {
	public Pointer name;
	public int height;
	public double weight;
	public User() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("name", "height", "weight");
	}
	public User(Pointer name, int height, double weight) {
		super();
		this.name = name;
		this.height = height;
		this.weight = weight;
	}
	public User(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends User implements Structure.ByReference {
		
	};
	public static class ByValue extends User implements Structure.ByValue {
		
	};
}
